batch_size: [1]
num_channels: [1, 3, 5]
kernel_size: [3, 5, 7, 9]
stride: [1, 2,5]
hidden_size: [1, 2, 4, 8, 16, 32, 64, 256, 512, 1024, 2048, 3072, 4096]
act_fn: "relu"
iters: 10
num_threads: 1
requires_grad: False
dropout: null
use_jit: False
use_cuda: False
device: "cpu"
device_idx: null
